/* piano_emulator.h — the C ABI of the physical-model piano.
 *
 * GENERATED by `ffi/generate-header.sh` (cbindgen 0.28.0) from `ffi/src/lib.rs`.
 * Do not edit: edit the Rust and regenerate. `ffi/tests/header.rs` fails if the
 * committed header and the source have drifted.
 *
 * Every function states the thread it belongs on. That contract is the reason
 * this header exists rather than a flat generated surface; see the module
 * comment in `ffi/src/lib.rs` for it in one piece.
 *
 * SPDX-License-Identifier: MIT
 */

#ifndef PIANO_EMULATOR_H
#define PIANO_EMULATOR_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/**
 * Version of this ABI. Bumped whenever a signature, a struct layout or the
 * meaning of a field changes; a host that loads the library dynamically should
 * compare it against `pe_abi_version` before calling anything else.
 */
#define PE_ABI_VERSION 2

/**
 * The engine's own sample rate, in Hz. A host running at exactly this rate
 * gets the resampler bypassed and is sample-for-sample what the offline
 * renderer produces.
 */
#define PE_ENGINE_SAMPLE_RATE 48000

/**
 * Largest velocity the engine takes. Anything above it is clamped.
 *
 * **The field has two lanes**, and they are the engine's own
 * (`piano_emulator::velocity_from_midi`), unchanged by the crossing:
 *
 * - `0 ..= 255` is a **MIDI 1.0 velocity**, the 7-bit number a keyboard sends
 *   (the lane is a byte wide so that no value the engine's own field could
 *   hold before it widened changed meaning). 0 is the silent press — the
 *   damper lifts and nothing is struck; anything over 127 is clamped to 127.
 * - `256 ..= 65535` is a **high-resolution velocity** in 1/512 of a MIDI step,
 *   which is where MIDI 2.0's 16 bits go (`SHIPPING.md` §4: the SL88 MK2 sends
 *   them). A 7-bit velocity `v` is exactly `v * 512` here, so both spellings
 *   of the same note play the same note.
 *
 * A host with a 7-bit source should use the first lane and can ignore the
 * second entirely. The ABI carried this field in 32 bits from version 1 so
 * that widening it would not move any struct offset; version 2 is the widening
 * itself, and it only added meaning to values that used to be clamped.
 */
#define PE_MAX_VELOCITY 65535

/**
 * What a `pe_event_t` is. Values outside this list are ignored rather than
 * rejected, so a newer host cannot crash an older library.
 */
enum pe_event_kind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
    /**
     * `key`, `vel`. Any nonzero velocity throws the hammer — velocity 1 is a
     * genuine pianissimo note and is never reinterpreted as a silent press
     * (`DECISIONS.md` 55). Velocity 0 means the same as `PE_EVENT_KEY_DOWN`.
     */
    PE_EVENT_NOTE_ON = 0,
    /**
     * `key`, `vel`, where `vel` is the **release** velocity: how fast the key
     * returns sets how fast the damper lands and how loud the key-off thump
     * is. A source with no measurement should send 64, not 0.
     */
    PE_EVENT_NOTE_OFF = 1,
    /**
     * `key`. The silent press: the damper lifts, nothing is struck.
     */
    PE_EVENT_KEY_DOWN = 2,
    /**
     * `value`, 0.0 up to 1.0 down, **continuous** — half-pedalling reaches the
     * dampers as the fraction it was played at. Map CC 64 to `cc / 127.0`, and
     * slew-limit it over ~15 ms if it came from a 7-bit controller
     * (`SHIPPING.md` §3).
     */
    PE_EVENT_SUSTAIN = 3,
    /**
     * `value` != 0.0 is down. A lever that either catches the raised damper
     * levers or does not; there is no half of it.
     */
    PE_EVENT_SOSTENUTO = 4,
    /**
     * `value` != 0.0 is down. Softens the hammer and drops one struck unison
     * string.
     */
    PE_EVENT_UNA_CORDA = 5,
    /**
     * Everything up, everything silent, immediately. Not a reset of the
     * instrument's clock — see `pe_reset`.
     */
    PE_EVENT_ALL_OFF = 6,
};
#ifndef __cplusplus
typedef uint32_t pe_event_kind;
#endif // __cplusplus

/**
 * Return codes. Zero is success and every failure is negative, so
 * `if (pe_load_preset_toml(...) != PE_OK)` is the whole of a caller's error
 * handling unless it wants to print `pe_last_error`.
 */
enum pe_status
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    PE_OK = 0,
    /**
     * A required pointer was null.
     */
    PE_ERR_NULL = -1,
    /**
     * An argument was out of range: a sample rate that is not a positive
     * finite number, a zero or absurd block size, a length with a null buffer.
     */
    PE_ERR_INVALID_ARGUMENT = -2,
    /**
     * The preset text is not valid UTF-8.
     */
    PE_ERR_UTF8 = -3,
    /**
     * The preset did not parse, or failed `Preset::validate`. The message —
     * which names the offending field — is at `pe_last_error`.
     */
    PE_ERR_PRESET = -4,
    /**
     * The destination buffer is too small; the call that returns a size tells
     * you how much it needs.
     */
    PE_ERR_BUFFER_TOO_SMALL = -5,
    /**
     * A panic was caught at the boundary. The library is still usable — no
     * unwinding crossed into C — but whatever was being done did not happen,
     * and this is a bug worth reporting.
     */
    PE_ERR_PANIC = -6,
};
#ifndef __cplusplus
typedef int32_t pe_status;
#endif // __cplusplus

/**
 * An engine, its boundary resampler and its preset. Opaque to C.
 *
 * The fields are in `UnsafeCell`s and are handed out one at a time rather than
 * through a `&mut` to the whole struct, because `pe_post_event` runs on a
 * different thread from `pe_render` and the two must never alias: the audio
 * thread reaches `audio`, the producer reaches `sender`, and the main thread
 * reaches the rest.
 */
typedef struct pe_engine pe_engine;

/**
 * One event, passed by value. 16 bytes, no padding, no pointers: it can be
 * built in a render callback, copied into a queue and sent over a wire.
 *
 * Fields not named by the event's kind are ignored; zero them anyway.
 */
typedef struct pe_event_t {
    /**
     * One of `pe_event_kind`. An unrecognised value is ignored.
     */
    uint32_t kind;
    /**
     * MIDI note number. A0 is 21 and C8 is 108; anything outside the 88 keys
     * is ignored rather than folded into the compass.
     */
    uint32_t key;
    /**
     * MIDI velocity in either of `PE_MAX_VELOCITY`'s two lanes; anything
     * above it is clamped.
     */
    uint32_t vel;
    /**
     * Pedal position, 0.0..=1.0. Ignored by the key events.
     */
    float value;
} pe_event_t;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Version of the ABI this library was built with; compare against
 * `PE_ABI_VERSION` from the header you compiled against.
 *
 * **Thread: any.**
 */
uint32_t pe_abi_version(void);

/**
 * Builds an engine for a host running at `host_sample_rate` Hz and rendering
 * at most `max_frames` frames per call.
 *
 * The engine starts on the built-in default preset — a complete, shippable
 * instrument — so a host that never calls `pe_load_preset_toml` still makes
 * a piano. `max_frames` sizes the resampler's chunk: a host that renders
 * exactly that many frames gets one resampler call per render. Rendering more
 * than `max_frames` in one call is still correct and still allocation-free.
 *
 * At exactly 48000 Hz the resampler is not built at all and the host's buffers
 * go straight to the engine.
 *
 * Returns null if the arguments are out of range, if the preset in the binary
 * is somehow unbuildable, or if the allocation fails. This is the only call
 * that allocates the instrument (88 voices, every coefficient), so it takes
 * hundreds of milliseconds and belongs nowhere near an audio thread.
 *
 * **Thread: main.**
 */
struct pe_engine *pe_create(double host_sample_rate, uint32_t max_frames);

/**
 * Frees an engine. Null is accepted and does nothing. After this the pointer
 * is dangling: nothing else may be called with it, and no render may be in
 * flight.
 *
 * **Thread: main.**
 *
 * # Safety
 * `engine` must be a pointer from `pe_create` that has not been destroyed.
 */
void pe_destroy(struct pe_engine *engine);

/**
 * Silences the instrument and clears the boundary filter's history: every
 * damper down, every string still, no partial resampler chunk left over. What
 * a host calls when the transport stops or the plugin is bypassed.
 *
 * It advances the engine by one 128-frame block, which is what flushes the
 * remainder left by the last render; that block is silence and is discarded.
 *
 * It deliberately does **not** reset the engine's frame counter, which seeds
 * the mechanism noise: two identical gestures a minute apart are not supposed
 * to make identical key noise, and a transport stop is not a new piano.
 * Rebuild the engine if you want that.
 *
 * **Thread: main** (it must not race a render).
 *
 * # Safety
 * `engine` must be a live pointer from `pe_create`.
 */
void pe_reset(struct pe_engine *engine);

/**
 * Loads a preset from TOML text, replacing the instrument.
 *
 * `text` is `len` bytes of UTF-8; it need not be NUL-terminated. The preset is
 * parsed **and validated** here (`DECISIONS.md` 52) — a negative decay rate, a
 * zero hammer mass, a table of the wrong length are all refused with a message
 * naming the field, which `pe_last_error` returns — so the audio thread
 * never sees a coefficient that has not been checked.
 *
 * On success the engine is rebuilt from scratch and everything sounding stops.
 * On failure the old instrument is untouched and still playable.
 *
 * This allocates and takes hundreds of milliseconds. It also invalidates the
 * event queue, so no `pe_post_event` may be in flight.
 *
 * **Thread: main.**
 *
 * # Safety
 * `engine` must be live, and `text` must point to `len` readable bytes.
 */
pe_status pe_load_preset_toml(struct pe_engine *engine,
                              const char *text,
                              size_t len);

/**
 * The message from the last failed call on this engine, as a NUL-terminated
 * UTF-8 string, or an empty string if the last call succeeded. Never null.
 *
 * The pointer is owned by the engine and is valid until the next call that can
 * fail, or until `pe_destroy`.
 *
 * **Thread: main.**
 *
 * # Safety
 * `engine` must be live.
 */
const char *pe_last_error(const struct pe_engine *engine);

/**
 * Renders `frames` frames into two non-interleaved channel buffers.
 *
 * `left` and `right` must each have room for `frames` floats. Any length is
 * accepted, including zero and lengths that are not a multiple of the engine's
 * 128-frame block: the stream is the same however it is cut up
 * (`DECISIONS.md` 47).
 *
 * At 48 kHz this is `Engine::process` and nothing else — no copy, no filter,
 * bit-for-bit what the offline renderer writes. At any other rate the output
 * is pulled through the boundary sinc, which asks the engine for as many
 * frames as it needs.
 *
 * Allocation-free, lock-free, syscall-free. The first call on a thread sets
 * that thread's ARM flush-to-zero bit, which is why it must be the audio
 * thread that calls it.
 *
 * **Thread: audio.** Never call it concurrently with itself or with any
 * main-thread entry point.
 *
 * # Safety
 * `engine` must be live, and both buffers must be writable for `frames`
 * floats.
 */
void pe_render(struct pe_engine *engine,
               float *left,
               float *right,
               uint32_t frames);

/**
 * Applies an event immediately, at the start of the next block the engine
 * renders.
 *
 * This is the plugin path: a host hands an AUv3 its MIDI on the audio thread,
 * in the render block's event list, so the events for a block are applied
 * before the block is rendered. Onsets therefore quantise to the engine's
 * 128-frame block, 2.7 ms (`DECISIONS.md` 55); sub-block placement is
 * `DISTRIBUTION.md` M2 and will not change this signature.
 *
 * An unknown kind, a key outside the 88, a velocity or pedal position out of
 * range: all ignored or clamped, never a crash.
 *
 * **Thread: audio.**
 *
 * # Safety
 * `engine` must be live.
 */
void pe_event(struct pe_engine *engine, struct pe_event_t event);

/**
 * Queues an event for the audio thread through the engine's pre-allocated SPSC
 * queue. Returns false if the queue is full (1024 events) or the event is not
 * one the engine understands; never blocks, never allocates.
 *
 * This is the standalone app's path: CoreMIDI callbacks and the UI post here,
 * and the audio thread drains the queue before every block it renders. A
 * plugin has no use for it — see `pe_event`.
 *
 * **Thread: any one thread.** The queue is single-producer: two threads
 * posting at once is undefined. Serialise them, or give each its own engine.
 *
 * # Safety
 * `engine` must be live.
 */
bool pe_post_event(struct pe_engine *engine, struct pe_event_t event);

/**
 * Writes the engine's state — the whole preset, as TOML — into `buf`, and
 * returns the number of bytes it needs.
 *
 * Call it with a null `buf` (or too small a `cap`) to ask for the size; call
 * it again with room and it writes that many bytes, **without** a trailing
 * NUL. Returns 0 only if the engine pointer is null or a panic was caught.
 *
 * This is what an AUv3's `fullState` should carry: the preset *text*, not a
 * reference to a file (`DISTRIBUTION.md` §Presets and state). Six kilobytes
 * gzipped in a project file is free, and a project saved today still opens
 * when the preset files have moved on. Restore it by handing the same bytes
 * back to `pe_load_preset_toml`.
 *
 * **Thread: main.**
 *
 * # Safety
 * `engine` must be live, and `buf` must be writable for `cap` bytes if it is
 * not null.
 */
size_t pe_save_state(struct pe_engine *engine, uint8_t *buf, size_t cap);

/**
 * The host rate this engine was built for, as it was given to `pe_create`.
 *
 * **Thread: any.**
 *
 * # Safety
 * `engine` must be live.
 */
double pe_host_sample_rate(const struct pe_engine *engine);

/**
 * Whether the boundary resampler is bypassed — true exactly when the host runs
 * at 48000 Hz, in which case the output is bit-identical to the engine's own.
 *
 * **Thread: any.**
 *
 * # Safety
 * `engine` must be live.
 */
bool pe_is_bypassed(const struct pe_engine *engine);

/**
 * Voices that are not idle, 0..=88 — the struck notes *and* every string
 * still ringing sympathetically with them, which is why one note can report
 * seventeen. For a meter or a test; not needed to play the instrument.
 *
 * **Thread: audio** (it reads the state the audio thread owns).
 *
 * # Safety
 * `engine` must be live.
 */
uint32_t pe_active_voices(const struct pe_engine *engine);

/**
 * The block size this engine was built for, as it was given to `pe_create`.
 *
 * **Thread: any.**
 *
 * # Safety
 * `engine` must be live.
 */
uint32_t pe_max_frames(const struct pe_engine *engine);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* PIANO_EMULATOR_H */
